### ISSUE TITLE
[Chapter 8] 직접 구현을 한 마디로 정의하면 뭐라고 설명해야 할까요?

### ISSUE THREAD

**Issue by holim0** [FEBookStudy/Grokking-Simplicity#1]
## 챕터 정보
- 챕터 번호: Chapter 8
- 챕터 제목: 계층형 설계 I

### 논의 내용: 계층형 설계에서 **직접 구현 패턴**을 각자 어떻게 받아 들이고 정의했는 지 궁금합니다.

저는 아래 코드와 같이 특정 기능을 구현할 때 그 기능을 구현한 함수 내 같은 계층의 함수를 호출하도록 구현하는 것으로 이해했습니다.

- ex) 저수준의 코드가 포함된 로직이라면 명시적으로 명칭을 부여하여 함수로 생성하고 추상화 단계를 한 단계 높이도록 구현

결론적으로 구체적인 구현을 추상화 단계를 높여 감추고 호출 화살표 길이는 줄이는 패턴이 맞는지?

### 관련 코드(optional)
```js
function freeTieClip(cart) {
    var hasTie     = false;
    var hasTieClip = false;
    for(var i = 0; i < cart.length; i++) {
        var item = cart[i];
        if(item.name === "tie")
            hasTie = true;
        if(item.name === "tie clip")
            hasTieClip = true;
    }
    if(hasTie && !hasTieClip) {
        var tieClip = make_item("tie clip", 0);
        return add_item(cart, tieClip);
    }
    return cart;
}

// Optimized freeTieClip function
function freeTieClip(cart) {
    var hasTie = isInCart(cart, "tie");
    var hasTieClip = isInCart(cart, "tie clip");
    
    if(hasTie && !hasTieClip) {
        var tieClip = make_item("tie clip", 0);
        return add_item(cart, tieClip);
    }
    return cart;
}

function isInCart(cart, name) {
    for(var i = 0; i < cart.length; i++) {
        if(cart[i].name === name)
            return true;
    }
    return false;
}
```

**Comment by wo-o29** [comment]
`함수는 자신과 비슷한 추상화 수준의 함수들을 사용해서 구현해야 한다.`
- 각 함수는 특정 계층에 속한다.
- 함수를 구현할 때 같은 계층이나 바로 아래 계층의 함수들만 사용한다.
- 각 함수가 하나의 추상화 수준에 집중할 수 있다.

**Comment by devwontory** [comment]
계층형 설계는 바로 아래 계층의 함수들만 사용해서 구현하는 것을 목표로 하고있고,
직접 구현 패턴은 그 계층형 설계를 구현하기 위한 패턴 1에 해당합니다.

저는 직접 구현 패턴의 목적을 여러 계층의 함수를 혼재해서 사용함으로서 복잡해지는 다이어그램을
하나의 계층의 함수를 사용하도록 수정해 구조적으로 단순화하는 데 있다고 이해했습니다. (화살표의 길이와는 무관하게)

그리고 각 계층은 또 하나의 추상화 벽(패턴 2)이라고도 볼 수 있을 것 같습니다.
추상화 벽 너머로 화살표가 존재한다는 것은 관심사 밖의 것을 신경쓰고 있다고 볼 수 있기 때문에,
여기에서 화살표의 길이를 줄이는 것을 한번 더 목표로 할 수 있을 것 같기도 하네요!

**Comment by holim0** [comment]
논의 종료로 이슈 닫겠습니다
