### ISSUE TITLE
[Chapter 8] p197 예제에서 어떤 코드가 더 좋다고 느껴지시나요??

### ISSUE THREAD

**Issue by wo-o29** [FEBookStudy/Grokking-Simplicity#2]
## 챕터 정보
- 챕터 번호: Chapter 8
- 챕터 제목: 계층형 설계 I
- 페이지 범위: p197

## 논의 사항
p197 예제에서 어떤 코드가 더 좋다고 느껴지시나요??

- 논의 내용: 제 생각은 배열 인덱스는 언어만 알면 충분히 이해가 가능하고, 더 개선이 필요하지 않다고 느끼는데 이걸 새로운 함수를 만들어서 추상화하니깐 억지로 1depth 더 늘어난 느낌이라고 느껴졌던 것 같네요

- `arraySet` 은 값을 바꾸니깐 카피-온-라이트 원칙을 추상화하는건 괜찮은 것 같은데 `arrayGet` 까지 필요한지는 잘 모르겠다…
- 이런 관점에서 화살표 길이가 중요할까요??

- 관련 코드(optional)
```js
// 1. 배열 인덱스를 직접 참조
function setPriceByName(cart, name, price){
  var i = indexOfItem(cart, name);
  if(i !== null){
    var item = cart[i];
    return arraySet(cart, i, setPrice(item.name, price));
  }

  return cart;
}

function indexOfItem(cart, name){
  for(var i = 0; i < cart.length; i++){
    if(cart[i].name === name){
      return i;
    }
  }
  return null;
}

// 2. 배열 인덱스를 참조하지 않음
function setPriceByName(cart, name, price){
  var i = indexOfItem(cart, name);
  if(i !== null){
    var item = arrayGet(cart, i);
    return arraySet(cart, i, setPrice(item, price));
  }
  return cart
}

function indexOfItem(cart, name){
  for(var i = 0; i < cart.length; i++){
    if(arrayGet(cart, i) === name){
      return i;
    }
  }
  return null;
}

function arrayGet(array, index){
  return array[index];
}
```

**Comment by holim0** [comment]
언급해주신 예시와 같이 단순 인덱스 접근에 대해 따로 함수로 빼서 추상화 단계를 높이는 것은 불필요하다고 생각합니다.

이렇게 생각한 이유
1. 인덱스 접근은 누구나 봤을 때 명확하게 동작을 알 수 있음.
2. 따라서 단순히 호출 화살표 길이를 줄이기 위한 추출로 느껴집니다.

다만, 특정 로직을 함수로 빼서 좀 더 선언적으로 어떤 로직이 수행되는 지 명확하게 표현이 된다면 빼는 것이 좋다고 생각합니다.

**Comment by devwontory** [comment]
저도 희제님과 같은 생각입니다!

선언적이고 이해하기 쉽게 작성될 수 있는 경우에는 매우 간단한 코드여도 따로 뺄 수 있다고 생각합니다.

책에서 설명한 의도는 공감이 되지만, 설득력 있는 예제는 아니었다고 생각해요.

**Comment by holim0** [comment]
논의 종료로 이슈 닫겠습니다
