### ISSUE TITLE
[Chapter 9] 하위 계층 코드에 대해 테스트 코드를 짜야할 것 같은데 어느정도까지 짜는게 적당할지?

### ISSUE THREAD

**Issue by wo-o29** [FEBookStudy/Grokking-Simplicity#3]
## 챕터 정보
- 챕터 번호: Chapter 9
- 챕터 제목: 계층형 설계 II
- 페이지 범위: p223 ~ p229

## 논의 사항

- 논의 내용: 책에서는 아래에 있는 코드를 테스트 하라고 하는데 조금 극단적으로 보면 `이런 함수`는 테스트 코드가 필요 없을 것 같은데 `이런 함수` 라는 것에 조금 더 명확한 기준이 있어야 할 것 같다.

- 아래 함수보다 조금 더 복잡한 함수가 있다고 했을 때, 나는 그 함수 또한 테스트 코드가 필요 없다고 주장했는데, 다른 분은 필요하다고 주장할 수 있는 상황이 나올 수 있을 것 같아서 명확한 기준이 있으면 좋을 것 같다는 생각이 들었던 것 같습니다!

- 저는 테스트 코드에 대한 경험이 없고 이제 `jest`를 학습하고 있어서 감이 잘 오지 않는데, 테스트 코드에 대한 경험이 있으시거나 테스트 코드 설계에 대한 본인의 기준이 있다고 하시면 공유해주시면 좋을 것 같아요🙃

- 관련 코드(optional)
```js
const sum = (a, b) => a + b;
```

**Comment by holim0** [comment]
개인적으로 테스트 코드 적용 범위는 각 팀 별로 논의하여 결정해야 된다고 생각합니다.

책에서는 계층의 아래로 갈수록 테스트가 쉽고 중요하다고 했는데, 언급 주신 저런 간단한 코드는 굳이 테스트 코드를 작성할 필요가 없을 거 같습니다.

어느정도 복잡한 로직이 들어가거나 비즈니스 로직이 연관되어 있는 함수나 그 함수에서 사용되는 바로 아래 계층의 함수에 대해서 테스트 코드를 작성하면 되지 않을까 생각합니다. (일정이 많다면 테스트 코드 적용 범위를 넓힐 수도 있겠네요)

현재 `jest`에 대해 공부하고 계신다고 했는데 공부하시다가 기준이 생긴다면 공유부탁드립니다!

**Comment by holim0** [comment]
갑자기 생각나서 코멘트 달아요.

논의할 때 Jest + MSW 기반으로 환경 구축할 때 polyfill 추가해야 하는 이슈에 대해 말씀드렸는데요. 관련 링크입니다.

공식 문서에 내용이 제가 겪었을 때랑 달라졌네요. 그 당시 공식 문서 대로 적용을 해도 안 되긴 했습니다.
- 문서 업데이트에 대한 코멘트 - https://github.com/mswjs/msw/issues/1796#issuecomment-1782594092 
- https://mswjs.io/docs/migrations/1.x-to-2.x/#frequent-issues

**Comment by holim0** [comment]
논의 종료로 이슈 닫겠습니다
