### ISSUE TITLE
[Chapter 13] 함수형 도구 체이닝으로 작은 단계를 나누어 작업을 수행할 때 성능적인 문제는 없을까요?? 

### ISSUE THREAD

**Issue by wo-o29** [FEBookStudy/Grokking-Simplicity#5]
## 챕터 정보
- 챕터 번호: Chapter 13
- 챕터 제목: 함수형 도구 체이닝
- 페이지 범위: P339

#### 논의 내용: 연습 문제에서 기존 코드는 한 번의 반복문 안에서 조건문을 통해 수량을 합산하는 데, 리팩토링 코드에서는 단계 별로 나누어서 작업을 수행하고 있습니다.

**리팩토링 코드를 봤을 때 단계를 작은 단위로 나누어서 각 단계가 어떤 역할을 하는지 한 눈에 볼 수 있어서 가독성이 좋은 것 같은데, 배열의 크기가 큰 경우에는 성능적으로 좋지 않을 것 같다는 생각이 드는데 다른 분들은 어떻게 생각하시는지 궁금합니다!**

#### 관련 코드(optional)
```js
// 기존 코드
function shoesAndSocksInventory(products) {
  var inventory = 0;

  for (var p = 0; p < products.length; p++) {
    var product = products[p];

    // 신발, 양말만 수량 추가
    if (product.type === "shoes" || product.type === "socks") {
      inventory += product.numberInInventory;
    }
  }

  return inventory;
}

// 리팩토링 코드
function shoesAndSocksInventory(products) {
  // 신발, 양말만 필터
  var shoesAndSocks = filter(products, function (product) {
    return product.type === "shoes" || product.type === "socks";
  });

  // 재고 수량만 추출
  var inventories = map(shoesAndSocks, function (product) {
    return product.numberInInventory;
  });

  // 재고 수량 합산
  return reduce(inventories, 0, plus);
}

```

**Comment by wo-o29** [comment]
눈에 보일 정도로 성능이 지장이 갈 수 있다면 바로 개선하지만, 그렇지 않다면 일단 함수형 도구 체이닝을 사용하여 가독성이 좋은 코드를 작성하고 성능이 체감되거나 테스트했을 때 문제라고 판단되면 그때 개선해보기!

**Comment by holim0** [comment]
리팩토링 후에도 결국 시간 복잡도로 따지면 데이터가 많아져도 O(n)이라 성능적으로 크게 문제되지 않을거 같습니다.

근데 데이터 크기가 정말 엄청나게 커지면 리팩토링 전/후 코드 모두 성능적으로 이슈가 발생할 수 있기 때문에 그때 최적화 방법을 찾아야 해야겠네요.

1. 반복문 내의 로직을 비동기 처리, web worker 사용
2. 리팩토링 전 코드에 대해서는 `products.length`를 밖으로 빼는 최적화
