### ISSUE TITLE
[Chapter 13] 함수형 도구로 map, filter, reduce 같은 별도의 함수가 필요한 이유는 무엇일까요?

### ISSUE THREAD

**Issue by devwontory** [FEBookStudy/Grokking-Simplicity#6]
## 챕터 정보
- 챕터 번호: Chapter 13
- 챕터 제목: 함수형 도구 체이닝

## 논의 사항
책에서 map, filter, reduce와 같은 함수들을 직접 구현하며 예시로 들고 있는데,
이 함수들이 함수형에서 왜 다시 구현되어야 했을까요?

책의 예제 코드는 실제 Lodash의 interface와 비슷해요.
Lodash에도 map과 같은 배열을 생성하는 함수가 구현이 되어있는데,
내장 메서드가 아닌 추가적인 인터페이스를 제공하게 된 이유가 무엇일지 궁금합니다. (어떤 이점이 있을까요?)

반대의 예시로는 Toss의 es-toolkit이 있는데
대체할 수 있는 네이티브 JavaScript API가 있거나, 아직 충분히 최적화되지 않은 경우,
Lodash와의 호환성을 위한 es-toolkit/compat으로 따로 분리하고 있어요.

> # Lodash와의 호환성
>
> ```tsx
> // es-toolkit/compat은 lodash와 100% 동일한 동작을 제공하도록 목표하고 있어요
> import { chunk } from 'es-toolkit/compat';
>
> // es-toolkit은 원래 chunk의 size로 0을 지원하지 않았어요
> chunk([1, 2, 3, 4], 0);
> // es-toolkit/compat은 lodash와 같은 []을 반환해요
> ```
>
> `lodash`와 최대 호환성을 위해서는 `es-toolkit/compat` 라이브러리를 사용하세요.
>
> `es-toolkit`은 매끄러운 마이그레이션을 보장하기 위해, 두 라이브러리 사이의 동작 차이가 없는 `es-toolkit/compat` 라이브러리를 개발하고 있어요. `lodash`와 동일한 API와 기능을 제공하여, 수월하게 마이그레이션을 할 수 있도록 도와줄 예정이에요.
>
> `es-toolkit/compat`은 실제 `lodash` 테스트 코드를 이용해서 테스트돼요.
>
> `es-toolkit/compat`은 원래 `es-toolkit`에 비해 런타임 퍼포먼스나 번들 크기가 최적은 아닐 수 있어요. 마이그레이션 중에 사용하는 도구로 생각해 주시고, 새로운 기능은 es-toolkit로 개발해주세요.
>
> ## 설계 원칙
>
> > **INFO**
> > `es-toolkit/compat` 설계 원칙의 방향성은 변경될 수 있어요.
>
> `es-toolkit/compat`은 다음과 같은 기능들에 대해서 `lodash`와 100% 동일한 기능을 제공하는 것을 목표로 해요.
>
> - `lodash`의 테스트 케이스로 작성된 기능
> - `@types/lodash` 또는 `@types/lodash-es`의 타입에서 추론할 수 있는 기능
>
> 아래와 같은 기능은 `es-toolkit/compat`에서 지원하지 않아요.
>
> - 암시적 타입 변환: 빈 문자열을 0 또는 false로 변환하는 것과 같은 동작
> - 어떤 경우에 특화된 구현: [sortedUniq](https://lodash.com/docs/4.17.15#sortedUniq)와 같이 정렬된 배열만 받는 함수
> - JavaScript 내장 객체의 프로토타입이 바뀐 경우에 대응하는 코드
> - JavaScript Realm에 대응하는 코드
> - 메서드 체이닝: `_(arr).map(...).filter(...)`와 같은 메서드 체이닝

## 참고 자료
- [Lodash / map](https://lodash.com/docs/4.17.15#map)
- [Lodash / filter](https://lodash.com/docs/4.17.15#filter)
- [Lodash / reduce](https://lodash.com/docs/4.17.15#reduce)
- [es-toolkit / Lodash와의 호환성](https://es-toolkit.slash.page/ko/compatibility.html)
- https://github.com/toss/es-toolkit/pull/514

**Comment by devwontory** [comment]
https://stackoverflow.com/questions/42861080/what-is-the-reason-to-use-lodash-underscore-map-function

JavaScript map과 Lodash map이 어떻게 다른지 답변달린 질문글인데,
함수형의 관점에서의 이유는 아닌 것 같네요..!
관련해서 의견 있으시면 커멘트 달아주시면 감사하겠습니다 ;)

**Comment by wo-o29** [comment]
공식적인 정보는 찾지 못했지만 기존 기능을 확장할 수 있고, 다른 lodash 함수들과 체이닝했을 때 lodash 인터페이스를 사용하여 일관성을 유지할 수 있다는 장점으로 만들지 않았을까? 생각이 드는 것 같아요🤔
