### ISSUE TITLE
[Chapter 15] 빠르게 두 번 클릭하면 잘못된 결과가 나오는 예시와 비슷한 경험을 겪으신 적 있나요?

### ISSUE THREAD

**Issue by holim0** [FEBookStudy/Grokking-Simplicity#7]
## 챕터 정보
- 챕터 번호: 15
- 챕터 제목: 타임라인 격리하기
- 페이지 범위: 429p~

#### 관련 코드(optional)

```js
function add_item_to_cart(name, price, quantity) {
    cart = add_item(cart, name, price, quantity);
    calc_cart_total();
}

function calc_cart_total() {
    total = 0;
    cost_ajax(cart, function(cost) {
        total += cost;
        shipping_ajax(cart, function(shipping) {
            total += shipping;
            update_total_dom(total);
        });
    });
}

```

**Comment by createhb21** [comment]
흐음.. 네 있었죠.
댓글 작성과 같은 경우에, 
"댓글 입력하기 " 버튼 클릭 후 mutate 상태라면 
액션 버튼을 disabled 하게 해서 버튼 클릭이 안되도록 리팩토링 했던 기억이 있습니다. (북마크하기 버튼같은 것도 비슷하네요)
추가적으로 abort controller 등을 활용하면
유저에게도 서버에게도 더 나은 경험을 제공할 수 있을 것 같아요.

ex) 
1. 모달을 열면 모달 내에서 어떠한 정보를 GET fetch하는 상황
2. 유저가 모달을 열었네? fetch 해야지
3. 근데 0.5초만에 모달 내용 확인도 안하고 모달을 닫아버리네?
4. fetch 취소하기 (abort controller 활용)

**Comment by wo-o29** [comment]
저도 효범님 말씀처럼 위와 같은 상황에서는 `isPending` 상태 같은걸로 데이터 패칭 중일때는 버튼을 `disable`하게 설정해서 막았던 것 같아요🙃

**Comment by createhb21** [comment]
@wontory useTransition, useDeferredValue

[React 18 useDeferredValue와 useTransition](https://doiler.tistory.com/83)

**Comment by holim0** [comment]
논의 종료로 이슈 닫겠습니다.
