### ISSUE TITLE
[Chapter 18] 옵저버 패턴을 사용하신 경험이 있으신가요??

### ISSUE THREAD

**Issue by wo-o29** [FEBookStudy/Grokking-Simplicity#8]
## 챕터 정보
- 챕터 번호: CHAPTER 18
- 챕터 제목: 반응형 아키텍처와 어니언 아키텍처
- 페이지 범위: p515

## 논의 사항
반응형 아키텍처 파트에서 옵저버 패턴(책에서는 감시자 `watcher`라는 표현을 사용)이 나오고 모달(`overlay-kit`), 토스트(`react-toastify`), 상태 관리(`jotai`, `zustand`), `react-hook-form` 등 다양한 라이브러리에서 옵저버 패턴을 사용하고 있는데 실제로 옵저버 패턴의 코드를 작성하신 경험이 있으신가요??

저는 저렇게 옵저버 패턴이 많이 사용되는거 보고 찍먹으로 토스트 컴포넌트 정도 구현해보려고 했던 것 같네요:)

## 참고 자료

- <a href="https://github.com/toss/overlay-kit/blob/main/packages/src/context/store.ts">toss/overlay-kit</a>
- <a href="https://github.com/fkhadra/react-toastify/blob/main/src/core/containerObserver.ts#L37">fkhadra/react-toastify</a>
- <a href="https://github.com/pmndrs/jotai/blob/main/src/vanilla/utils/atomFamily.ts#L32">pmndrs/jotai</a>
- <a href="https://github.com/pmndrs/zustand/blob/main/src/vanilla.ts#L58">pmndrs/zustand</a>
- <a href="https://github.com/react-hook-form/react-hook-form/blob/master/src/utils/createSubject.ts#L11">react-hook-form/react-hook-form</a>

**Comment by holim0** [comment]
이전에 개발 진행할 때 zustand의 `subscribe` ([참고](https://github.com/pmndrs/zustand?tab=readme-ov-file#readingwriting-state-and-reacting-to-changes-outside-of-components))를 사용해서 옵저버 패턴은 적용해본적이 있습니다.
외부에서 주입되는 값에 따라 zustand 스토를 초기화시켜줘야 했었는데 그때 zustand의 `subcribe` 메서드를 사용했습니다.

책의 예시처럼 함수가 단일 책임을 가지는 방향으로 옵저버 패턴을 적용해본적은 없는 것 같습니다.. 앞으로 잘 적용해봐야겠어요

**Comment by wo-o29** [comment]
> 이전에 개발 진행할 때 zustand의 `subscribe` ([참고](https://github.com/pmndrs/zustand?tab=readme-ov-file#readingwriting-state-and-reacting-to-changes-outside-of-components))를 사용해서 옵저버 패턴은 적용해본적이 있습니다. 외부에서 주입되는 값에 따라 zustand 스토를 초기화시켜줘야 했었는데 그때 zustand의 `subcribe` 메서드를 사용했습니다.
> 
> 책의 예시처럼 함수가 단일 책임을 가지는 방향으로 옵저버 패턴을 적용해본적은 없는 것 같습니다.. 앞으로 잘 적용해봐야겠어요

오호 `subcribe`메서드로 스토어 초기화도 가능한가요?! 요렇게 되어있어서 `subscribe` 메서드 사용할 때 인자로 넣은 함수만 구독 해제될 것 같은데 따로 추가 설정같은게 있는건가용??
```ts
const subscribe: StoreApi<TState>['subscribe'] = (listener) => {
    listeners.add(listener)
    // Unsubscribe
    return () => listeners.delete(listener)
  }
```

저는 `zustand` 찍먹해볼 때 `get`, `set`만 사용하고 `subcribe`메서드를 사용해본 적은 없었던 것 같은데 희제님은 어떤 상황이여서 `subcribe` 메서드를 사용하셨었나요??

**Comment by createhb21** [comment]
유저 인증 관리를 위해서 AuthService라는 클래스를 만들어 싱글톤 패턴으로 사용하곤 하는데
AuthService 사용하는 패턴 자체를 옵저버 패턴이라고 보기는 어려운 것 같은데,
AuthService 내에서는 일부 옵저버 패턴을 이용하는 것 같아요.

**Comment by holim0** [comment]
> > 이전에 개발 진행할 때 zustand의 `subscribe` ([참고](https://github.com/pmndrs/zustand?tab=readme-ov-file#readingwriting-state-and-reacting-to-changes-outside-of-components))를 사용해서 옵저버 패턴은 적용해본적이 있습니다. 외부에서 주입되는 값에 따라 zustand 스토를 초기화시켜줘야 했었는데 그때 zustand의 `subcribe` 메서드를 사용했습니다.
> > 책의 예시처럼 함수가 단일 책임을 가지는 방향으로 옵저버 패턴을 적용해본적은 없는 것 같습니다.. 앞으로 잘 적용해봐야겠어요
> 
> 오호 `subcribe`메서드로 스토어 초기화도 가능한가요?! 요렇게 되어있어서 `subscribe` 메서드 사용할 때 인자로 넣은 함수만 구독 해제될 것 같은데 따로 추가 설정같은게 있는건가용??
> 
> ```ts
> const subscribe: StoreApi<TState>['subscribe'] = (listener) => {
>     listeners.add(listener)
>     // Unsubscribe
>     return () => listeners.delete(listener)
>   }
> ```
> 
> 저는 `zustand` 찍먹해볼 때 `get`, `set`만 사용하고 `subcribe`메서드를 사용해본 적은 없었던 것 같은데 희제님은 어떤 상황이여서 `subcribe` 메서드를 사용하셨었나요??

히스토리 관리 측면에서 답변 남깁니다.

제가 사용한 상황 및 적용 방법은 다음과 같습니다.
#### 상황
1. url path 변경에 따른 zustand 스토어가 초기화되지 않아 이전 데이터가 존재
ex) /banana/service1 -> /melon/service2

위 상황은 업무 환경이 특수한 환경이라 발생되었습니다.

#### 적용 방법
1. `initialState`를 생성하여 zustand 스토어 생성 시에 초기화 
2. `subscribe`를 통해 url 변경됨에 따라서 zustand 스토어를 `initialState`로 초기화

초기화 방법은 zustand 공식문서의 가이드대로 적용했습니다. ([참고](https://zustand.docs.pmnd.rs/guides/how-to-reset-state))
